version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"


  kafka:
      image: wurstmeister/kafka
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  graphana:
    image: grafana/grafana-oss
    ports:
        - "3000:3000"
    volumes:
      - ./graphana/:/var/lib/graphana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SERVER_DOMAIN=localhost
#  currently ELK through compose unresolved but have implemented through local installation

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    ports:
#      - 9200:9200
#      - 9300:9300
#    volumes:
#      - ./elk/elastic-data:/user/share/elasticsearch/data
#  logstash:
#    image:  docker.elastic.co/logstash/logstash:7.15.0
#    environment:
#      - XPACK.MONITORING.ENABLED=false
#    ports:
#      - 9600:9600
#    volumes:
#      - ./elk/logstash:/usr/share/logstash/pipeline
#      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.15.0
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch
#    environment:
#      - ELASTICSEARCH_URL=http://localhost:9200
#  filebeat:
#    image:  docker.elastic.co/beats/filebeat:7.15.0
#    user: root
#    volumes:
#      - ./elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
#      -   /var/run/docker.sock:/var/run/docker.sock
#      -   /var/lib/docker/containers:/var/lib/docker/containers
#    command: -e
#    depends_on:
#      - elasticsearch
#volumes:
#      elastic_data: {}

