spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/axon
  application:
    name: BLOG-SERVICE
eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone:  http://localhost:8761/eureka
